services:

  docmost:
    image: docmost/docmost:latest
    container_name: docmost
    depends_on:
      - db
      - redis
    environment:
      APP_URL: http://localhost:3000
      APP_SECRET: 38b07d089a725c94ab0940b50d4f607cecc9749b7d42cdbf8ab75bf2510f976b
      DATABASE_URL: postgresql://docmost:STRONG_DB_PASSWORD@db:5432/docmost?schema=public
      REDIS_URL: redis://redis:6379
    ports:
      - 3467:3000
    volumes:
      - docmost_data_volume:/app/data/storage
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: STRONG_DB_PASSWORD
    volumes:
      - docmost_db_volume:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    container_name: docmost_redis
    volumes:
      - docmost_redis_volume:/data
    restart: unless-stopped

volumes:
  docmost_data_volume:
    name: docmost_data_volume
    driver: local
    driver_opts:
      type: none
      device: /mnt/synonas1/docker-volumes-docs/docmost/data
      o: bind
  docmost_db_volume:
    name: docmost_db_volume
    driver: local
    driver_opts:
      type: none
      device: /mnt/synonas1/docker-volumes-docs/docmost/db
      o: bind
  docmost_redis_volume:
    name: docmost_redis_volume
    driver: local
    driver_opts:
      type: none
      device: /mnt/synonas1/docker-volumes-docs/docmost/redis
      o: bind
