services:

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - TZ=Australia/Sydney
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - qbittorrent_config_volume:/config
      - qbittorrent_downloads_volume:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

volumes:
  qbittorrent_config_volume:
    name: qbittorrent_config_volume
    driver: local
    driver_opts:
      type: none
      device: /mnt/synonas1/docker-volumes/qbittorrent/config
      o: bind
  qbittorrent_downloads_volume:
    name: qbittorrent_downloads_volume
    driver: local
    driver_opts:
      type: none
      device: /mnt/synonas1/docker-volumes/qbittorrent/downloads
      o: bind
