services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Australia/Sydney
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - config:/config
      - ${CENTRAL_VOLUME_STORAGE}/qbittorrent2/downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

volumes:
  config:
