services:

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Sydney/Australia
    volumes:
      - config:/config
    ports:
      - 9696:9696
    restart: unless-stopped

volumes:
  config:
    name: prowlarr_config
