services:

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - TZ=Sydney/Australia
    volumes:
      - prowlarr_config_volume:/config
    ports:
      - 9696:9696
    restart: unless-stopped

volumes:
  prowlarr_config_volume:
    name: prowlarr_config_volume
    driver: local
    driver_opts:
      type: none
      device: /mnt/synonas1/docker-volumes/prowlarr/config
      o: bind
