services:

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: "https://vaultwarden.lejohndary.com"
    volumes:
      - vaultwarden_data_volume:/data
    ports:
      - 9445:80

volumes:
  vaultwarden_data_volume:
    name: vaultwarden_data_volume
    driver: local
    driver_opts:
      type: none
      device: /mnt/synonas1/docker-volumes/vaultwarden/data
      o: bind
