services:

  guacd:
    image: guacamole/guacd:latest
    container_name: guacd
    restart: unless-stopped

  mysql:
    image: mysql:latest
    container_name: guac_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # Change this
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: guacamole_pass # Change this
    volumes:
      - guacamole_db_volume:/var/lib/mysql

  guacamole:
    image: guacamole/guacamole:latest
    container_name: guacamole
    depends_on:
      - guacd
      - mysql
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: mysql
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: guacamole_pass # Change this
    ports:
      - "8082:8080"
    restart: unless-stopped

volumes:
  guacamole_db_volume:
    name: guacamole_db_volume
    driver: local
    driver_opts:
      type: none
      device: /mnt/synonas1/docker-volumes/guacamole/db
      o: bind
