services:

  guacd:
    image: guacamole/guacd:latest
    container_name: guacd
    restart: unless-stopped

  mysql:
    image: mysql:latest
    container_name: guac_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # Change this
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: guacamole_pass # Change this
    volumes:
      - mysql_data:/var/lib/mysql

  guacamole:
    image: guacamole/guacamole:latest
    container_name: guacamole
    depends_on:
      - guacd
      - mysql
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: mysql
      MYSQL_DATABASE: guacamole_db
      MYSQL_USER: guacamole_user
      MYSQL_PASSWORD: guacamole_pass # Change this
    ports:
      - "8082:8080"
    restart: unless-stopped

volumes:
  mysql_data:
