services:

  filestash:
    image: machines/filestash:latest
    container_name: filestash
    ports:
      - "8334:8334"
    volumes:
      - filestash_data:/data
    restart: unless-stopped

volumes:
  filestash_data:
    name: filestash_data
