services:

  db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=aDx!WyRRz%69
      - MYSQL_PASSWORD=aDx!WyRRz%69
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  app:
    image: nextcloud
    container_name: nextcloud
    restart: always
    ports:
      - 8081:80
    links:
      - db
    volumes:
      - html:/var/www/html
    environment:
      - MYSQL_PASSWORD=aDx!WyRRz%69
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db

volumes:
  html:
    name: nextcloud_html
  db:
    name: nextcloud_db
