services:

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    env_file:
      - .env
    ports:
      - 8461:80
    volumes:
      - pgadmin_data_volume:/var/lib/pgadmin
    restart: unless-stopped

volumes:
  pgadmin_data_volume:
    name: pgadmin_data_volume
    driver: local
    driver_opts:
      type: none
      device: /mnt/synonas1/docker-volumes/pgadmin/data
      o: bind
