services:

  fileflows:
    image: revenz/fileflows:latest
    container_name: fileflows
    ports:
      - 19200:5000
    environment:
      - TempPathHost=/tmp
      - TZ=Australia/Sydney
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - fileflows_temp_volume:/temp
      - fileflows_data_volume:/app/Data
      - fileflows_logs_volume:/app/Logs
      - fileflows_common_volume:/app/common

      - fileflows_fujifilm_x100vi_consume_volume:/fujifilm-x100vi-consume
      - fileflows_fujifilm_x100vi_processed_volume:/fujifilm-x100vi-processed

      - fileflows_media_consume_volume:/media-consume
      - fileflows_media_processed_volume:/media-processed

    restart: unless-stopped

volumes:
  fileflows_temp_volume:
    name: fileflows_temp_volume
    driver: local
    driver_opts:
      type: none
      device: /mnt/synonas1/docker-volumes/fileflows/temp
      o: bind
  fileflows_data_volume:
    name: fileflows_data_volume
    driver: local
    driver_opts:
      type: none
      device: /mnt/synonas1/docker-volumes/fileflows/data
      o: bind
  fileflows_logs_volume:
    name: fileflows_logs_volume
    driver: local
    driver_opts:
      type: none
      device: /mnt/synonas1/docker-volumes/fileflows/logs
      o: bind
  fileflows_common_volume:
    name: fileflows_common_volume
    driver: local
    driver_opts:
      type: none
      device: /mnt/synonas1/docker-volumes/fileflows/common
      o: bind

  fileflows_fujifilm_x100vi_consume_volume:
    name: fileflows_fujifilm_x100vi_consume_volume
    driver: local
    driver_opts:
      type: none
      device: /mnt/synonas1/docker-volumes/fileflows/fujifilm-x100vi-consume
      o: bind
  fileflows_fujifilm_x100vi_processed_volume:
    name: fileflows_fujifilm_x100vi_processed_volume
    driver: local
    driver_opts:
      type: none
      device: /mnt/synonas1/docker-volumes/fileflows/fujifilm-x100vi-processed
      o: bind

  fileflows_media_consume_volume:
    name: fileflows_media_consume_volume
    driver: local
    driver_opts:
      type: none
      device: /mnt/synonas1/docker-volumes/fileflows/media-consume
      o: bind
  fileflows_media_processed_volume:
    name: fileflows_media_processed_volume
    driver: local
    driver_opts:
      type: none
      device: /mnt/synonas1/docker-volumes/fileflows/media-processed
      o: bind
