services:

  redis:
    image: redis:latest
    container_name: outline_redis
    restart: unless-stopped

  postgres:
    image: postgres:15.2-alpine3.17
    container_name: outline_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: outline
    volumes:
      - outline_db_volume:/var/lib/postgresql/data
    restart: unless-stopped

  wk-outline:
    image: outlinewiki/outline:0.72.0-3
    container_name: outline
    command: sh -c "yarn db:migrate --env production-ssl-disabled && yarn start"
    environment:
      - DATABASE_URL=postgres://user:pass@postgres:5432/outline
      - DATABASE_URL_TEST=postgres://user:pass@postgres:5432/outline-test
      - REDIS_URL=redis://redis:6379
      - AWS_S3_UPLOAD_BUCKET_NAME=outline-bucket
    env_file:
      - ./env.outline
      - ./env.oidc
    volumes:
      - outline_data_volume:/var/lib/outline/data
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  wk-oidc-server:
    image: vicalloy/oidc-server
    container_name: outline_oidc
    volumes:
      - outline_oidc_fixtures_volume:/app/oidc_server/fixtures:z
      - outline_oidc_db_volume:/app/db:z
      - outline_oidc_static_root_volume:/app/static_root:z
    env_file:
      - ./env.oidc-server
    restart: unless-stopped

  nginx:
    image: nginx
    container_name: outline_nginx
    ports:
      - 8282:80
    volumes:
      - outline_nginx_volume:/etc/nginx/conf.d/:ro
      - outline_static_root_volume:/uc/static_root:ro
    depends_on:
      - wk-outline
      - wk-oidc-server
    restart: unless-stopped

volumes:
  outline_db_volume:
    name: outline_db_volume
    driver: local
    driver_opts:
      type: none
      device: /mnt/synonas1/docker-volumes/outline/db
      o: bind
  outline_data_volume:
    name: outline_data_volume
    driver: local
    driver_opts:
      type: none
      device: /mnt/synonas1/docker-volumes/outline/data
      o: bind
  outline_oidc_fixtures_volume:
    name: outline_oidc_fixtures_volume
    driver: local
    driver_opts:
      type: none
      device: /mnt/synonas1/docker-volumes/outline/oidc-fixtures
      o: bind
  outline_oidc_db_volume:
    name: outline_oidc_db_volume
    driver: local
    driver_opts:
      type: none
      device: /mnt/synonas1/docker-volumes/outline/oidc-db
      o: bind
  outline_oidc_static_root_volume:
    name: outline_oidc_static_root_volume
    driver: local
    driver_opts:
      type: none
      device: /mnt/synonas1/docker-volumes/outline/oidc-static-root
      o: bind
  outline_nginx_volume:
    name: outline_nginx_volume
    driver: local
    driver_opts:
      type: none
      device: /mnt/synonas1/docker-volumes/outline/nginx
      o: bind
  outline_static_root_volume:
    name: outline_static_root_volume
    driver: local
    driver_opts:
      type: none
      device: /mnt/synonas1/docker-volumes/outline/static-root
      o: bind
