services:

  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    ports:
      - 8012:8096
    environment:
      - PUID=1026
      - GUID=100
      - TZ=Australia/Sydney
    volumes:
      - jellyfin_config_volume:/config
      - jellyfin_cache_volume:/cache
      - "/mnt/synonas1/homes/jdansev/Media Library:/media"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

volumes:
  jellyfin_config_volume:
    name: jellyfin_config_volume
    driver: local
    driver_opts:
      type: none
      device: /mnt/synonas1/docker-volumes/jellyfin/config
      o: bind
  jellyfin_cache_volume:
    name: jellyfin_cache_volume
    driver: local
    driver_opts:
      type: none
      device: /mnt/synonas1/docker-volumes/jellyfin/cache
      o: bind
