services:

  autossh:
    image: jnovack/autossh
    container_name: autossh
    env_file:
      - .env
    environment:
      - SSH_REMOTE_PORT=22
      - SSH_MODE=-R
      - SSH_BIND_IP=0.0.0.0
      - SSH_TARGET_PORT=22
      - SSH_KEY_FILE=/id_rsa
    restart: unless-stopped
    volumes:
      - /home/jdansev/.ssh/id_rsa:/id_rsa
    dns:
      - 8.8.8.8
      - 1.1.1.1
