services:

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9444:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data_volume:/data
    restart: unless-stopped

volumes:
  portainer_data_volume:
    name: portainer_data_volume
    driver: local
    driver_opts:
      type: none
      device: /mnt/synonas1/docker-volumes/portainer/data
      o: bind
