services:

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - 9444:9443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    restart: unless-stopped

volumes:
  data:
    name: portainer_data
