services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    ports:
      - 8090:8090
    volumes:
      - beszel_data_volume:/beszel_data
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  beszel_agent:
    image: henrygd/beszel-agent:latest
    container_name: beszel_agent
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      PORT: 45876
      KEY: 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIwErNH2DXMH/LFHz02+BMAES2Q2DLeAxi/k3nZAL2cu'
      FILESYSTEM: /dev/sda1 # set to the correct filesystem for disk I/O stats
    restart: unless-stopped

volumes:
  beszel_data_volume:
    name: beszel_data_volume
    driver: local
    driver_opts:
      type: none
      device: /mnt/synonas1/docker-volumes/beszel/data
      o: bind
