services:

  frigate:
    image: ghcr.io/blakeblackshear/frigate:stable
    container_name: frigate
    shm_size: "64mb"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - frigate_config_volume:/config
      - frigate_media_volume:/media/frigate
      - type: tmpfs
        target: /tmp/cache
        tmpfs:
          size: 1000000000
    ports:
      - "5000:5000"
      - "8554:8554" # RTSP feeds
      - "8555:8555/tcp" # WebRTC over tcp
      - "8555:8555/udp" # WebRTC over udp
    environment:
      FRIGATE_RTSP_PASSWORD: ${PASSWORD}
    restart: unless-stopped

volumes:
  frigate_config_volume:
    name: frigate_config_volume
    driver: local
    driver_opts:
      type: none
      device: /mnt/synonas1/docker-volumes/frigate/config
      o: bind
  frigate_media_volume:
    name: frigate_media_volume
    driver: local
    driver_opts:
      type: none
      device: /mnt/synonas1/docker-volumes/frigate/media
      o: bind
