services:

  minio:
    image: docker.io/bitnami/minio:2022
    container_name: minio
    ports:
      - 9900:9000
      - 9901:9001
    volumes:
      - minio_data_volume:/data
    environment:
      - TZ=Sydney/Australia
      - MINIO_ROOT_USER=${USERNAME}
      - MINIO_ROOT_PASSWORD=${PASSWORD}
      - MINIO_DEFAULT_BUCKETS=${DEFAULT_BUCKETS}
    restart: unless-stopped

volumes:
  minio_data_volume:
    name: minio_data_volume
    driver: local
    driver_opts:
      type: none
      device: /mnt/synonas1/docker-volumes-misc/minio/data
      o: bind
