services:

  glance:
    container_name: glance
    image: glanceapp/glance
    volumes:
      - ./config:/app/config
      - glance_assets_volume:/app/assets
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8966:8080
    env_file: .env

volumes:
  glance_assets_volume:
      name: glance_assets_volume
      driver: local
      driver_opts:
        type: none
        device: /mnt/synonas1/docker-volumes/glance/assets
        o: bind
