services:

  dockge:
    image: louislam/dockge:1
    container_name: dockge
    ports:
      - 5050:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/stacks:/opt/stacks
      - ${DOCKER_BIND_MOUNT_PATH}/dockge/data:/app/data
    environment:
      - DOCKGE_STACKS_DIR=/opt/stacks
    restart: unless-stopped
